### ISSUE TITLE
SlidingTabStyle flexible doesn't work as expected

### ISSUE THREAD

**Issue by yccheok** [erthru/SlidingTabsExample#5]
Thank you for creating sliding tab example.

I notice that `SlidingTabStyle` `flexible` doesn't work as expected, as it just merely multiple `view.frame.width` with a 0.2 constant. Hence, when the text is too short or too long, it looks weird.

![Screen Shot 2020-08-29 at 3 20 30 AM](https://user-images.githubusercontent.com/308276/91607541-9d3bb400-e9a6-11ea-95a5-e7a7c591645d.png)

May I know, do you have any good solution for such? Thanks.

**Comment by AlejandroMuralles** [comment]
I solved it like this

`let title = titles[indexPath.row]`
`let lenght = title.count`
`return CGSize(width: CGFloat(lenght*10 + 20), height: CGFloat(heightHeader))`
