### ISSUE TITLE
Needs to update to support iOS 14

### ISSUE THREAD

**Issue by delmarz** [erthru/SlidingTabsExample#6]
Not working on iOS 14, especially when dealing horizontal scroll

**Comment by blackdolphin8888** [comment]
> Not working on iOS 14, especially when dealing horizontal scroll

same problem :((

**Comment by nievesjesus** [comment]
I open a PR with this fix: https://github.com/erthru/SlidingTabsExample/pull/7 @delmarz  @dung-ht
